name: flutter_downloader_vm
description: Powerful plugin making it easy to download files with custom notification title.
version: 0.0.1
repository: https://github.com/Dacyz/flutter_downloader_vm
issue_tracker: https://github.com/Dacyz/flutter_downloader_vm/issues
maintainer: Dacyz (@Dacyz)

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0
